project:
  type: book
  output-dir: _book
  post-render: quarto render --profile slides

number-depth: 1

book:
  reader-mode: false
  title: "Coursetitle"
  chapters:
    - index.qmd
    - part: "First Part"
      chapters: 
       - Course1/index.qmd
    - part: "Second Part"
      chapters: 
       - Course2/index.qmd

format:
  live-html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
