project:
  type: book
  output-dir: _book
  post-render: quarto render --profile slides

number-depth: 1

book:
  reader-mode: false
  title: "Python Summer"
  chapters:
    - index.qmd
    - part: "Course 1: Python Basics & Objects"
      chapters: 
       - Course1/index.qmd
    - part: "Course 2: Functions, Lists, Dictionaries & Classes"
      chapters: 
       - Course2/index.qmd
    - part: "Course 3: Files, Data & Practice"
      chapters: 
       - Course3/index.qmd
    - part: "Course 4: Numpy"
      chapters: 
       - Course4/index.qmd
    - part: "Course 5: Pandas"
      chapters: 
       - Course5/index.qmd

format:
  live-html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
